### ISSUE TITLE
User agent issue

### ISSUE THREAD

**Issue by YokohamaAIart** [maxkrivich/SlowLoris#13]
Hi hi,
I just bumped int that 1 minute ago:

└─# slowloris -u http://www.xxxxxxxxxxxxxxx.com -c 100 -s
Attack info:
	Target: http://www.xxxxxxxxxxxxxxxxxx.com:80/(00.210.000.11)
	Connection count: 100
	Mode (silent): True
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/usr/local/lib/python3.9/dist-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

Any clue please?

**Comment by maxkrivich** [comment]
I suggest reporting this bug [here](https://github.com/hellysmile/fake-useragent). Unfortunately, there's nothing to fix on slowloris side unless you want to get rid of the library or implement proper handling of these types of exceptions. I'm open to any solutions in case if you have something in your mind that would solve the problem.

**Comment by maxkrivich** [comment]
Here is the link to the issue https://github.com/hellysmile/fake-useragent/issues/113

**Comment by YokohamaAIart** [comment]
Many thanks.

ZL.

    On Friday, September 10, 2021, 05:12:59 AM GMT+8, Max ***@***.***> wrote:  
 
 


Here is the link to the issue hellysmile/fake-useragent#113

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
