### ISSUE TITLE
PyPi long description format

### ISSUE THREAD

**Issue by maxkrivich** [maxkrivich/SlowLoris#2]
Publication issue:
On PyPi in description tag [PySlowLoris](https://pypi.python.org/pypi/PySlowLoris) happens something weird. Probably the bug somewhere in setup.py at line 48.
https://github.com/maxkrivich/SlowLoris/blob/c15732aadf70dc179817b6f54692d200db9b5a03/setup.py#L47-L49

README.rst was generated by module [m2r](https://pypi.python.org/pypi/m2r).

**Comment by maxkrivich** [comment]
@cclauss if you can find a solution let me know.

**Comment by cclauss** [comment]
What exactly don't you like?
* target: alt: lines?
* horizontal lines?
* formatting of command line params?
* MIT is missing for license?

**Comment by maxkrivich** [comment]
@cclauss I hope what that's would look like README.md if it is possible.
