### ISSUE TITLE
SSL call fails

### ISSUE THREAD

**Issue by AndrewMossCSA** [maxkrivich/SlowLoris#6]
- Ubuntu 18.04LTS
- Python 2.7

Using default tag: latest
latest: Pulling from maxkrivich/pyslowloris
402ae6c1c9cf: Pull complete
b9e2ecdf64ec: Pull complete
94f147cb24f1: Pull complete
d5be6b7b6169: Pull complete
4cd7baadf299: Pull complete
d7f197c3ce0d: Pull complete
0f8eb4f70e15: Pull complete
3d3cf6ec9dc0: Pull complete
Digest: sha256:b15859ddfbcc61da7a7c4f5376b26e08cee5c2f45806640417927a3d57e98b7e
Status: Downloaded newer image for maxkrivich/pyslowloris:latest

running with the following command results in an error

 docker run --rm -it maxkrivich/pyslowloris -u https://web3.domainremoved.com -p 443 -s 300

/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
2019-05-01 11:39:44,836 [ERROR] PySlowLoris: 'server'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/PySlowLoris/slowloris/targetinfo.py", line 62, in get_info
    self.server = r.headers['Server']
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'server'
Traceback (most recent call last):
  File "/usr/local/bin/slowloris", line 9, in <module>
    load_entry_point('PySlowLoris==0.1.29', 'console_scripts', 'slowloris')()
  File "build/bdist.linux-x86_64/egg/PySlowLoris/cli.py", line 147, in main
  File "build/bdist.linux-x86_64/egg/PySlowLoris/cli.py", line 133, in print_info
  File "build/bdist.linux-x86_64/egg/PySlowLoris/cli.py", line 122, in print_table
  File "build/bdist.linux-x86_64/egg/PySlowLoris/cli.py", line 122, in <genexpr>
TypeError: object of type 'NoneType' has no len()

**Comment by maxkrivich** [comment]
Yeah, that's the problem. I'll try to fix 😄 
https://github.com/maxkrivich/SlowLoris/blob/master/TODO.md#new-features

**Comment by AndrewMossCSA** [comment]
Thank you - let me know if you need me to test

**Comment by anoduck** [comment]
Similar, but different cause for the failure. In my situation I recieve:

```
 SNIMissingWarning: An HTTPS request has been made, but the SNI (Subje
ct Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause va
lidation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-us
age.html#ssl-warnings                 
  SNIMissingWarning 

InsecurePlatformWarning: A true SSLContext object is not available. T
his prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve 
this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings                                                    
  InsecurePlatformWarning

Certificate did not match expected hostname: 
```  

This was in the docker container as well. If I installed it from pip, I recieved the "No Module named 'Queue'" error.
