### ISSUE TITLE
No module named Queue

### ISSUE THREAD

**Issue by JCastix** [maxkrivich/SlowLoris#9]
- **OS and version used:** <VERSION> 
Win 10 64
- **Python runtime used:** <VERSION> 
3.7 64
- **Library version used:** <VERSION> 
0.1.3.0

# Description of the issue:

Getting: no module named Queue
# Code sample exhibiting the issue:

# Console log of the issue:

No module named 'Queue'
Stack trace:
 >  File "C:\SlowLorisTest.py", line 18, in <module>
 >    from PySlowLoris import TargetInfo, SlowLorisAttack
Loaded '__main__'
Loaded 'runpy'
The program 'python.exe' has exited with code 1 (0x1).

**Comment by maxkrivich** [comment]
Yeah, that's because the queue module was renamed in py3. The lib is quite old and I have no time to add compatibility of both versions of python. Just try to use it under a docker container.
```bash
$ docker pull maxkrivich/pyslowloris
$ docker run --rm -it maxkrivich/pyslowloris [-h] [-u URL] [-p PORT] [-s SOCKET_COUNT]
```

**Comment by JCastix** [comment]
Ok, thanks!

ex nihilo aliquid

________________________________

**Comment by anoduck** [comment]
Received the same error under Alpine Linux with python3. Does work with python2 using pip2 to install.

**Comment by maxkrivich** [comment]
@JCastix try to check the new version.
